### ISSUE TITLE
Need to add a shell script to start this plugin in startup

### ISSUE THREAD

**Issue by vishnugt** [vishnugt/youtube-dl-plugin#2]
A script which would look like [this](https://github.com/vishnugt/Right-Click-and-Shortcuts/blob/master/keyboard.bat)

We need to come up with something that doesn't involve hardcoding the location, but instead, everything should be done automatically once they install it

**Comment by vishnugt** [comment]
Should research the possibility of being OS independent or a way to support both linux and windows

**Comment by amandal799** [comment]
I am ineterested in this issue. Can i work on it. I have got this fixed on ubuntu and haven't tried on windows till now.

**Comment by vishnugt** [comment]
Yeah, sure.  Please send a PR, I'll review and approve it.
